### ISSUE TITLE
Attributes as Variable, Constraint and Model attributes

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#114]
The attributes we define are not subtypes of variable, constraint or model attributes because the value passed is described sometimes with a number, sometimes with a variable and a number and sometimes with 2 variables and a numbers.
The variables should be mapped with the `index_map` when going through the `CachingOptimizer` layer for instance.
The fact that we pass several things can be handled by wrapping them in a `struct` and the fact that the variables need to be mapped can be by defining a `map_indices`.
In fact, we could even reuse the `MOI.ScalarAffineTerm` and `MOI.ScalarQuadraticTerm`.
Moreover, adding derivatives for for multiple coefficients could be done with `MOI.ScalarAffineFunction` and `MOI.ScalarQuadraticFunction`.
In fact, this would even work with variable bridges out of the box with `bridged_function`.
If you pass a `MOI.ScalarAffineFunction` containing, say,  `2x + 3y` and `x` is bridged into `a - b` then `bridged_function` will transform this into `2a - 2b + 3y` which is actually what we want.

**Comment by matbesancon** [comment]
Was this one closed by the last PR?

**Comment by blegat** [comment]
Yes, closed by https://github.com/jump-dev/DiffOpt.jl/pull/128
