### ISSUE TITLE
Creating a MOI Optimizer layer

### ISSUE THREAD

**Issue by be-apt** [jump-dev/DiffOpt.jl#12]
referring these projects:
- https://github.com/JuliaOpt/Dualization.jl/blob/master/src/MOI_wrapper.jl
- https://github.com/tomasfmg/ParametricOptInterface.jl/blob/master/src/ParametricOptInterface.jl
- https://github.com/joaquimg/QuadraticToBinary.jl/blob/master/src/moi.jl

todo:
- [x] PR #19 
- [x] #13 
- [x] #14 
- [x] #22

**Comment by joaquimg** [comment]
This is complete since the delivery of the project.
