### ISSUE TITLE
Typo in conic getter for BackwardOut objective

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#122]
`dQ_end_i` should be one of the two operands of the last line of
https://github.com/jump-dev/DiffOpt.jl/blob/2a373d07b1c45b02b5d03c9699ee6b23f70297bc/src/diff_opt.jl#L307-L309

**Comment by joaquimg** [comment]
`return - dQ_i_end + dQ_end_i `
because of:
https://github.com/jump-dev/DiffOpt.jl/blob/2a373d07b1c45b02b5d03c9699ee6b23f70297bc/src/diff_opt.jl#L359
