### ISSUE TITLE
BackwardOut dA for inequalities

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#127]
Looking at (8) of the paper, shouldn't the line
https://github.com/jump-dev/DiffOpt.jl/blob/a2ab035596d0296e23fd7cbdff368615fa90cb57/src/diff_opt.jl#L489
be `λ[i] * (dλ[i] * z - λ[i] * dz)` ?

**Comment by matbesancon** [comment]
mmh, @joaquimg ?
