### ISSUE TITLE
Handle GreaterThan constraints

### ISSUE THREAD

**Issue by AKS1996** [jump-dev/DiffOpt.jl#14]
can be easily cast to LessThan constraints - at least for current QPTH method

**Comment by matbesancon** [comment]
either by casting everything to LessThan, or by keeping a behavior for each type of constraint (a sense of the derivative for example), and keeping a dictionary of the senses. I don't think Dualization keeps senses but adds appropriate slack variables to get equalities everywhere

**Comment by AKS1996** [comment]
will need to support `MOI.Zeros` in a similar way
