### ISSUE TITLE
Integration with Flux.jl

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/DiffOpt.jl#147]
As a standard tool of machine learning, [Flux.jl](https://github.com/FluxML/Flux.jl) is widely used in Julia.

It would be really helpful if users can use DiffOpt.jl conveniently with Flux.jl.

A notable example would be [cvxpylayers](https://github.com/cvxgrp/cvxpylayers).

If it is already possible, please share a simpler and clearer tutorial for this feature :)

**Comment by joaquimg** [comment]
As you pointed out in https://github.com/jump-dev/DiffOpt.jl/issues/168
There is one in the ReLU example.

**Comment by JinraeKim** [comment]
Sorry but I don't think the ReLU example indicates that DiffOpt.jl is integrated with Flux.jl as users have to manually write the `rrule` part carefully.

**Comment by joaquimg** [comment]
An issue or PR with a concrete alternative design would be much appreciated.

**Comment by JinraeKim** [comment]
> An issue or PR with a concrete alternative design would be much appreciated.

I see.
Thank you for your reply :)
