### ISSUE TITLE
Fix CI badge

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/DiffOpt.jl#160]
We have 3 options:

 - allow CI to ignore nightly fails
 - remove nightly from CI
 - remove badge

Otherwise, the user gets the impression there is something off

**Comment by matbesancon** [comment]
yes I would like to do this for other projects too, nightly has been broken for weeks now.
I haven't yet found an option to ignore nightly on actions, what people do it seems is add a separate workflow, have a CI one for the main checks, and a copy for nightly

**Comment by blegat** [comment]
Let's remove nightly from CI
