### ISSUE TITLE
Understanding ReLU example

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/DiffOpt.jl#168]
Hi, developers!
Thank you for your good package as always. I'm really interested in DiffOpt.jl, but it's a bit hard to understand so I'm glad to see more examples.

My observations are:
1) The ReLU example realises a ReLU layer by a (convex) optimisation problem
2) `rrule` in the example corresponds to the usual backpropagation rule, typically observed from ML packages.

I wonder if I understood the [ReLU example](https://jump.dev/DiffOpt.jl/dev/examples/custom-relu/) correctly.
Thanks!

**Comment by joaquimg** [comment]
You are correct!
Feel free to suggest improvements through PR's.
