### ISSUE TITLE
Any timeline for being registered in General?

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/DiffOpt.jl#175]

**Comment by matbesancon** [comment]
Now that we simplified the dependencies, this should be feasible soon indeed.
@blegat we should make a release before #166 or do you think we should wrap it up before?

**Comment by blegat** [comment]
I don't think https://github.com/jump-dev/DiffOpt.jl/pull/166 should break the interface. Anyway, a v0.0.1 release should be fine :)

**Comment by matbesancon** [comment]
well then let's go
