### ISSUE TITLE
Supporting MOI linear5test

### ISSUE THREAD

**Issue by be-apt** [jump-dev/DiffOpt.jl#20]
Not covering [MOI.linear5test](https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Test/contlinear.jl#L627) as of now
Not a lot of solvers support `MOI.delete` or `MOI.ScalarCoefficientChange` methods

**Comment by blegat** [comment]
For these solvers, you can use an `MOIU.CachingOptimizer` in between DiffOpt and the solver

**Comment by be-apt** [comment]
this can be closed. linear5test (https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Test/contlinear.jl#L913) works in https://github.com/jump-dev/DiffOpt.jl/blob/master/test/solver_interface.jl#L4
