### ISSUE TITLE
Test more exotic cases

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#202]
Currently, we only test giving QPs in standard form and use QPDiff or giving CPs in standard for and use ConicDiff.
The user might not give these form and get errors as it's not tested.
We should add tests for this, e.g., adding a constraint in NormOneCone or NormInfinityCone to QPDiff (as it can be rewritten as LP).
This might encouter missing setters and getters for the DiffOpt attributes for a few bridges that we should add. Similar to
https://github.com/jump-dev/DiffOpt.jl/blob/3d7e38530fc0d1251abd4a25c279a82c48556f34/src/bridges.jl#L1-L32

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/DiffOpt.jl/issues/102
