### ISSUE TITLE
Renaming QPDiff and ConicDiff

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#215]
It's inconsistent to have `QP` and `Conic`. We should probably have `QP` and `CP`. Moreover, `DiffOpt.QPDiff` and `DiffOpt.CPDiff` are redundant, what about renaming them `DiffOpt.QP` and `DiffOpt.CP` ?

**Comment by matbesancon** [comment]
I'm not a fan of defining types with abbreviations, it's harder to parse for beginners. What about
DiffOpt.QuadraticForm, DiffOpt.ConicForm, or DiffOpt.Quadratic DiffOpt.Conic?

**Comment by blegat** [comment]
Yes, MOI is also without abbreviations. The issue with Quadratic is that unless we say `QuadraticProgram`, I'm not sure it's clear that we mean convex quadratic objective and linear constraints

**Comment by joaquimg** [comment]
QuadraticProgram and ConicProgram are good for me
