### ISSUE TITLE
Add MOI standard tests

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/DiffOpt.jl#27]
Do like this package here: https://github.com/joaquimg/QuadraticToBinary.jl/blob/master/test/runtests.jl

This will make the API more robust and closer to what JuMP needs.

**Comment by AKS1996** [comment]
almost all tests added - left with "From MOI ncqcp", "From MOI qcp", and integer tests

**Comment by matbesancon** [comment]
@joaquimg should we close this one now that MOI tests are there
