### ISSUE TITLE
Remove dependency on SCS.jl  

### ISSUE THREAD

**Issue by AKS1996** [jump-dev/DiffOpt.jl#38]
As of this writing, the slack and dual optimal values are fetched from SCS.jl `sol` variable
The values obtained via `ConstraintPrimal` and `ConstraintDual` differ from the values that give correct result
specifically slack and dual optimal values for POS constraint differ - for other constraints it just needs sorting according to cone types
 
i've added comments in https://github.com/AKS1996/DiffOpt.jl/pull/37

**Comment by AKS1996** [comment]
once this is fixed, we should be able to differentiate using any conic solver

**Comment by matbesancon** [comment]
seems merged now
