### ISSUE TITLE
Add JuMP support

### ISSUE THREAD

**Issue by be-apt** [jump-dev/DiffOpt.jl#44]
right now one can use DiffOpt using MOI only. what'll be required to make it work w/ JuMP?
also, is there any other feature that should be added/corrected in DiffOpt before we begin?

**Comment by be-apt** [comment]
i guess half of this is already done, thanks to @joaquimg 
if we can set/get ForwardOut/ForwardIn using JuMP (without to the need to do `diff_opt = backend(model).optimizer.model`) it would be even better

**Comment by joaquimg** [comment]
Exactly! This was closed by #81
