### ISSUE TITLE
Example PSD not similar to the PSD one?

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/DiffOpt.jl#48]
In testset "Differentiating a simple PSD", the example does not seem identical to the notebook pointed to (the vector `b` is not present)

**Comment by matbesancon** [comment]
It does not match https://github.com/AKS1996/jump-gsoc-2020/blob/master/diffcp_sdp_0_py.ipynb

**Comment by AKS1996** [comment]
i think thats' correct. although just noticed that a lot of links to specifc lines of `contconic.jl` aren't valid now. need a lot of changing

**Comment by matbesancon** [comment]
where is the `b = np.array([0.0, 1.4142135623730951, 1.4142135623730951, 0.0, 1.4142135623730951, 0.0])` in our test? Or is it not there because of the representation of the matrix?

**Comment by AKS1996** [comment]
true. the problem variables might be confusing w/ the matrices `A`, `b`, `c` (`c` [here](https://github.com/jump-dev/DiffOpt.jl/blob/master/test/MOI_wrapper.jl#L839) in the problem isn't the same as `c` in the conic form).
try printing `b` [here](https://github.com/jump-dev/DiffOpt.jl/blob/master/src/MOI_wrapper.jl#L512) and it should give the required matrix
```
b = [0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
```

**Comment by matbesancon** [comment]
OK then a comment in the test could be good to explain that we don't take the same form as input
