### ISSUE TITLE
backward_conic! is actually a forward conic

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/DiffOpt.jl#58]
backward_conic! takes the input perturbation as parameter (dA, db, dc) and computes the perturbation of the output (dx, dy, ds), the name is misleading since it is executing a forward differentiation.

Also does not need the bang since it is not mutating anything. This also holds for the plain backward.

**Comment by matbesancon** [comment]
Things to fix:
1. Having a proper backward! for conic. Ideally the same method just checking whether the problem is a QP or conic problem
2. While we are at it, implementing forward also for QPs
3. Remove bangs

**Comment by joaquimg** [comment]
This was closed by #81
