### ISSUE TITLE
Implementing derivatives in terms of ChainRules

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/DiffOpt.jl#8]
Once the derivatives can be computed with respect to parameters at different places of the optimization problem, these derivatives should be expressed in terms of ChainRules, and specifically https://github.com/JuliaDiff/ChainRulesCore.jl

**Comment by AKS1996** [comment]
that'll be great! it'll help make the project AD compatible

**Comment by AKS1996** [comment]
opened a PR https://github.com/JuliaDiff/ChainRulesCore.jl/issues/210
