### ISSUE TITLE
Unify notation for conic and QP

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/DiffOpt.jl#80]
- Always use x for primal variables
 - use c for the linear part of objective (instead of q)
 - choose between y and lambda for duals ? (nu is also used in qp mode)
 - write basic equations from papers in docs

**Comment by matbesancon** [comment]
@joaquimg was this one fixed with #81 ?

**Comment by joaquimg** [comment]
For the user yes!
Internally no, internally we are following each paper notation.

**Comment by joaquimg** [comment]
I think it is enough to close this
